name: CI Backend Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [main, backend ]
  pull_request:
    branches: [main, backend ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
        #Using python
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
        #Setup
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install -y $(grep -o ^[^#][[:alnum:]-]* "packages.list")
          pip install flake8 pytest
          pip install -r requirements.txt
        
        #Linting
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 flake8 --ignore E501 --exclude __pycache__,./bulletjournal/migrations,./website/settings.py
          
        #Testing
      - name: Test with pytest
        run: |
         pytest --exitfirst --verbose --failed-first \
         --cov=. --cov-report html
